### ISSUE TITLE
箱をおさえる

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#1]

**Comment by RooandQoo** [comment]
何処がいいんだろう

**Comment by asonas** [comment]
どんな条件だといいんでしょうかね？
- デイイベントで借りられる
- プロジェクタがある
- それなりにインターネットに繋がる
  - なかったらWiMAXかな

こんなかんじかしら

**Comment by RooandQoo** [comment]
必要なのはそのくらいだと思います。以前言ってた渋谷？の箱はどうなんでしょ

**Comment by asonas** [comment]
渋谷OTOかな（なんかWebページ死んでる。。。
http://www.shibuya-oto.com/ (追加したYO!/mactkg)
あそこはプロジェクターが無い＆狭いから映せるところもないので少し厳しみかも。

Weekend Garage Tokyoっていうところもよさそうでした。
http://weekendgaragetokyo.jp/index.html
厳密には箱ではなく、カフェだけど広くて雰囲気もよかったです。
箱じゃないので、パーティ的に貸しきるので僕らが箱代を出すことにはならないのが気が楽
具体的な値段はこのあたり。最安で2000円、飲み放題とかいれると4500円ぐらい
http://weekendgaragetokyo.jp/pdf/party_plan.pdf

あとは渋谷に乙っていうのもあります
http://kinoto.jp/
ここは弊社同僚もたまに箱として使ってるので割りとおすすめな感じです。
弊社同僚から言えば幾らか箱代が安くなる予感もしている。

**Comment by asonas** [comment]
よく考えたら飲み放題とかあんまいらないのか。

**Comment by RooandQoo** [comment]
酒代は参加者が飲みたいだけ従量課金でいいかと

**Comment by mactkg** [comment]
渋谷OTOのページあった、ドメイン変わってるっぽい
http://www.shibuya-oto.com

**Comment by e-jigsaw** [comment]
ちゃらいので今日 http://4sq.com/1pE6C14 にきてるんですけど、なかなかよさそう

**Comment by e-jigsaw** [comment]
sabacoで仮

**Comment by asonas** [comment]
sabaco。
第1希望日が5月31日と、第2希望日6月1日で申し込みしました。

続報あればまたここに書きますね

**Comment by asonas** [comment]
http://sabaco.jp/contact/ 
よく見たら5月31日って空いてないのかな（予約受付中って書いてない

**Comment by asonas** [comment]
sabacoの人から連絡きて、31日で予約できるとのことでした。
書面での契約が必要なので、僕がお店に言って契約してこようと思います。

また日時ですが15時から20時ぐらいを想定してるけどよいかな？

**Comment by e-jigsaw** [comment]
よいとおもいまーす！

**Comment by asonas** [comment]
茶箱で契約しました。
15時〜21時で取ってあります。
値段変わらないので目一杯とりました。時間途中で終わるのもOKとのことです。

**Comment by asonas** [comment]
箱代振り込んだし、closeします。
