### ISSUE TITLE
茶箱にききたいこと

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#10]
- インターネットありますか？
- 受付はどのようにできますか？

**Comment by asonas** [comment]
インターネット、プロジェクタはある。
受付は聞くの忘れちゃった。メールして聞きます

**Comment by e-jigsaw** [comment]
:sparkles:

**Comment by asonas** [comment]
メールした。
再入場は無限にできるかどうか聞いてみた。

**Comment by asonas** [comment]
インターネットは観客の人たちでも使えるとのこと〜
tumblrが捗る

**Comment by RooandQoo** [comment]
Issueの趣旨とはずれるかもしれないんだけど、PCDJしたい時ってパソコンだけ持ってけばいいのかな。

**Comment by asonas** [comment]
機材のことも聞いてみますね。

**Comment by asonas** [comment]
memo #13 

週末もろもろやります

**Comment by asonas** [comment]
もろもろお返事帰ってきた。

## 機材

http://sabaco.jp/faq/
ここから使いたい機材を申し込む
CDJ、ターンテーブル、ミキサーを選べる
1週間前にはメールで連絡をする

## 着替え

DJや観客のコスプレや衣装の着替えなどはトイレにカーテンをつけるので可能
小さなスペースなのでなるべく簡単な衣装が望ましいとのことです

## UST

あるよ〜
ハッシュタグを事前に連絡すれば登録してくれるとのこと

## 当日スケジュール

当日は出演者は14時から入店して接続チェックができます
完全撤収は21時終了から30分後、21時半までです

## 再入場

基本的に不可、道に迷った時など特別な場合おいて許可されるとのこと。

**Comment by asonas** [comment]
## 機材について

聞き出しを始めておきたいのでインタビューしていこう
http://sabaco.jp/faq/

| name | 機材の持ち込みか常設機材 | 機材の名前 |
| --- | --- | --- |
| asonas | 持ち込み | iPad + Z1 + KaossPad |
| RooandQoo | 持ち込み | PCDJ + DDJ-WeGo |
| jigsaw | 持ち込み | PCDJ + S2 |
| mactkg | 持ち込み | PCDJ + Z1 + X1 |
| maccha | 持ち込み | PCDJ + DDJ-WeGo |
| toihrk | 持ち込み | PCDJ + DDJ-SB |
| y_taq | 常設機材 | CDJ Pioneer CDJ-1000mk3 x2 DJ Mixer Pioneer DJM-800 |
| xen | 常設機材 | CDJ Pioneer CDJ-1000mk3 x2 DJ Mixer Pioneer DJM-800 |
| frkout | 常設機材 | CDJ Pioneer CDJ-1000mk3 x2 DJ Mixer Pioneer DJM-800 |
| 八嶋 | (問い合わせ) | 常設機材にPCDJできるタンテがないかを確認する |

ゲストの方々には僕の方から連絡しますね

音響機器的なものでマイクも借りれるか一応聞く

**Comment by e-jigsaw** [comment]
S2抱えて行けばいいのかな！？

**Comment by asonas** [comment]
かもんかもん〜

**Comment by e-jigsaw** [comment]
更新しました

**Comment by mactkg** [comment]
とりあえずアップデートしました

@asonas 
Z1の代わりに会場のミキサーを使うとか出来ないんですかね？と思いましたけどDJM-800はTRAKTOR PROとそんなに連携できないみたいですね。。。

**Comment by RooandQoo** [comment]
CDJ Pioneer CDJ-1000mk3 x2
DJ Mixer Pioneer DJM-800
でおなしゃす。

**Comment by asonas** [comment]
@mactkg たぶんできるんじゃないかなー？

**Comment by RooandQoo** [comment]
すいません！CDJ-1000はUSBが刺さらないらしいので機材持ち込みます！！

**Comment by RooandQoo** [comment]
持ち込み予定機材がまっちゃさんと被ってる

**Comment by asonas** [comment]
とりあえず、機材の情報出揃ったので茶箱さんに連絡しますー

**Comment by asonas** [comment]
機材に関して連絡ずみ。
当日のUSTのハッシュタグも設定してもらいました。

別途なにか連絡したいことあればReopenします
