### ISSUE TITLE
sabacoのレンタル料

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#11]
6万円になります。
http://sabaco.jp/faq/

出演者のみなさまから徴収しようと思うのですがいかがでしょうかー？

内訳もちょっと考慮して、社会人5人学生4人(小山からといくんとご友人2名、mactkgくん)なので、
社会人が1万円、学生が2500円、という具合にしようと考えてます。

すっかり忘れてて（すみません...）月末までに支払わないとダメなので、
1. 出演者のみんなで割り勘をする
2. 社会人1万円、学生2500円にする

の2点で合意が取れれば、僕の方からsabacoさんに振込をしようと思います。

**Comment by e-jigsaw** [comment]
:ok_woman:

**Comment by maccha** [comment]
OKでーす！

**Comment by RooandQoo** [comment]
りょうかいでーす

**Comment by mactkg** [comment]
社会人の皆さんありがとうございます！！！！！

**Comment by asonas** [comment]
といくんにも確認とれたので、これでいこうと思いますー。

また僕にお金の渡し方ですが、銀行振込か渋谷にいる僕をつかまえて手渡しなどでお願いします

三菱東京UFJ銀行
中目黒支店 普通 0132820
フジワラユウヤ

なる早で振り込んでもらえると助かります...!

**Comment by toihrk** [comment]
(なかなかissue読めてなくてすみませんー 社会人パワーありがとうございます！)

**Comment by asonas** [comment]
といくんと小山高専の2人とまっくんからは受取済み

**Comment by asonas** [comment]
macchaさん確認済〜

**Comment by e-jigsaw** [comment]
これ明日とかに渡しに行っていいですか

**Comment by asonas** [comment]
お、いいよ〜。どこで落ち合う？

**Comment by e-jigsaw** [comment]
御社まで伺います？？ :bowtie:

**Comment by asonas** [comment]
それでもよか〜
何時頃くる？

**Comment by e-jigsaw** [comment]
アッ、今日アレなんで明日でもよいですか

**Comment by asonas** [comment]
いいよ〜

**Comment by e-jigsaw** [comment]
ウィッス、終業後に行こうとおもいます

**Comment by asonas** [comment]
らじゃ

**Comment by RooandQoo** [comment]
初任給出たら振り込みます(∩´｡ω゜`∩)

**Comment by asonas** [comment]
お〜け〜

**Comment by asonas** [comment]
とりあえず全員から回収完了しました。
みなさん、ありがとうございました!!!当日頑張りましょう〜〜〜〜〜〜〜〜〜
