### ISSUE TITLE
出演に興味ある人がいるとのこと

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#12]
https://www.facebook.com/asonas.P/posts/718468008196403?stream_ref=10

メッセージで返事待ち

**Comment by asonas** [comment]
参考資料
- 30m DJ 顧問 a.k.a. @asonas (Ani-son)
- 50m DJ 部長 a.k.a. @RooandQoo (trance)
- 40m DJ 副部長 a.k.a. @e-jigsaw (IDOLCORE)
- 30m @mactkg (INTERNET)
- 40m @hirokiTOI (HARDCORE TECHNO?)
- 30m @maccha (game music)
- 30m TBD (invitee)
- 30m TBD (invitee)
- 50m frkout
- 合計 330m / 360m

あと1人ぐらいは行ける。

**Comment by RooandQoo** [comment]
今誰を呼んでるんでしたっけ？
小山の子もいる？

**Comment by asonas** [comment]
小山高専が2人
furaji君の友人が1人
frkout

という感じですね

**Comment by RooandQoo** [comment]
30m DJ 顧問 a.k.a. @asonas (Ani-son)
50m DJ 部長 a.k.a. @RooandQoo (trance)
40m DJ 副部長 a.k.a. @e-jigsaw (IDOLCORE)
30m @mactkg (INTERNET)
40m @hirokiTOI (HARDCORE TECHNO?)
30m @maccha (game music)
30m 小山の子A
30m 小山の子B
30m ふらじの友人
50m frkout
合計 360m / 360m

うまくいくとこうか。

**Comment by asonas** [comment]
ですね！

**Comment by asonas** [comment]
TTを組むときにジャンルで同じような人たちをまとめるといいかなぁ、と思うのでゲストの人のジャンルも確認中です

**Comment by RooandQoo** [comment]
30m DJ 顧問 a.k.a. @asonas (Ani-son)
50m DJ 部長 a.k.a. @RooandQoo (trance)
40m DJ 副部長 a.k.a. @e-jigsaw (IDOLCORE)
30m @mactkg (INTERNET)
40m @hirokiTOI (HARDCORE TECHNO?)
30m @maccha (game music)
30m y_taq(ハードコア？
30m XEN(トランス？
30m ふらじの友人
50m frkout

**Comment by asonas** [comment]
ふらじくんの友人OKもらって自己紹介もついかした
