### ISSUE TITLE
受付をどうするか

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#14]
DJが持ち回しで受付を交代でやるってのが一番簡単かな。
その際にお金の所在をどうするか、封筒に入れて管理？
固定で受付の人を誰かにお願いする方法もありそう。

Doorkeeperで事前払いとかを使えば受付で金銭のやりとりがなくなるのでいいなぁと思うけど、あんまりいい筋じゃない気もする。
みんながDoorkeeperを使えるわけでもない気がするし、結局受付でお金の受け渡しが必要そう

なにかいい案とか意見があれば、募集したみ

**Comment by RooandQoo** [comment]
DJたちとは別にスタッフを用意するのが普通かなー。
スタッフも含めて持ち回りで受付やればいいと思いまっす。

**Comment by RooandQoo** [comment]
Tweetviteとかで登録したら割引！とかいう感じのイベントもあるけど、基本的にお金は入るときに払うものだし、Doorkeeperとか使うと「当日ふらっと入れるのかな？」みたいな疑問を抱かれそうな気もする

**Comment by asonas** [comment]
お〜け〜。
それじゃあスタッフを募集しますかー。

どなたかあてがあれば嬉しみ...!!

**Comment by RooandQoo** [comment]
興味ありそうな高専女子にコソーリとファーオを出しましょう

**Comment by asonas** [comment]
ファーオ、お願いしてもいいですか？

**Comment by RooandQoo** [comment]
高専女子全然知らない問題

**Comment by asonas** [comment]
あっはい。

**Comment by asonas** [comment]
それじゃ、僕の方でも興味ありそうな人を探してみますね。

**Comment by RooandQoo** [comment]
各自1人ずつ連れてくる感じにしますか

**Comment by RooandQoo** [comment]
たままるさんに声かけましたが予定ありとのこと
とりあえずきゃなばーどの返事待ちです
僕からは以上です

**Comment by asonas** [comment]
tmdさんに声かけてみた〜。

**Comment by asonas** [comment]
ダメでした...

**Comment by asonas** [comment]
たままるさんってtmdさんのことか...

**Comment by RooandQoo** [comment]
そうでした…

**Comment by RooandQoo** [comment]
きゃなばーどOK出ました

**Comment by asonas** [comment]
:+1:

**Comment by asonas** [comment]
めそさんに打診しました（週末までにはお返事しますとのこと〜）

**Comment by asonas** [comment]
めそさんダメだった。。。

**Comment by asonas** [comment]
きゃなさんと出演者でまわす方向でいこうと思います。

**Comment by e-jigsaw** [comment]
:tada:
