### ISSUE TITLE
打ち上げ

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#15]
場所
- 高田馬場付近

予算
- 3000円しないくらい

時間
- 10時開始が望ましい

メンツ
- るーく
- あそなす
- じぐそう
- とい
- まっくん
- まっちゃ
- frkout
- XEN
- y_taq
- 八嶋

**Comment by RooandQoo** [comment]
海峡にした
http://www.kaikyo.co.jp/cn3/cn8/pg69.html

**Comment by mactkg** [comment]
:tada:
