### ISSUE TITLE
#2の日程調整

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#16]

**Comment by asonas** [comment]
ｯｼｬｵﾗ

**Comment by e-jigsaw** [comment]
えっと9月12日あたり数週間ぐらい以外はいけます

**Comment by RooandQoo** [comment]
8月9月のよてい

8/16,17 C86
8/23,24 帰省
8/30(Sat) YAPC
9/6(Sat) ハードコアタノシー
9/13,14 なし
9/20(Sat) RubyKaigi 2014
9/27,28 ULTRA JAPAN(いかないで大阪いってる可能性アリ)

**Comment by RooandQoo** [comment]
日曜開催も視野

**Comment by asonas** [comment]
9月22日(日)？（23日は秋分の日）

**Comment by asonas** [comment]
22日 is Monday -月曜始まりのカレンダーの罠-

**Comment by asonas** [comment]
- 夏だし学生に来てほしい
- 土曜日の売り切れ具合

というのを考慮して
8月31日(日)の13時から19時でやろうかなぁと

**Comment by asonas** [comment]
8月31日(日)で移行と思います。
13時から19時で箱の予約します。

**Comment by RooandQoo** [comment]
予約したのでクローズします

**Comment by mactkg** [comment]
先を越された
