### ISSUE TITLE
#1 のKPT

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#17]

**Comment by asonas** [comment]
## Keep
- 動員的な意味での最小開催コストで最大楽しめた
- めっちゃよかった
- TJ最高だった
- sorahのVJよかった
- 解散が早かった
  - 店長さんに褒められた
- DJやりたい！って人が増えた
- 同じ高専出身の友人が来てくれた
- 高専関係じゃない人も来てくれた
- USTあってよかった
- 茶箱のサイズ感よかった
- 初回にしては20人近くもきてくれて嬉しかった。

## Problem
- TJの使い方わからない人たくさんいた
  - APIの弾切れ
- 連絡手段がまばらで結構大変だった
- 機材の使い方よくわかってなかった
  - 音量調整など
- 遅刻しない

## Try
- TJの改良
  - UI
  - 告知
- MLやGithubなどで連絡をまとめる
  - GHの通知微妙なのでMLかなぁ
- DJの人数を増やしたい
  - 2日開催？
  - #2-1, #2-2？
  - 1人30分で12人?
- 録画録音機材あるとよさそう
  - 定点で正面と横の2箇所からあるとよさそう

**Comment by e-jigsaw** [comment]
:sushi:

**Comment by asonas** [comment]
他の人もなにか書きたいことあれば書いていいのよ

**Comment by asonas** [comment]
ブログ書いたし、閉じます。おつかれさまでした
