### ISSUE TITLE
箱の予約をする

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#18]
なるはやで

**Comment by mactkg** [comment]
![screen shot 2014-06-16 at 4 35 14 pm](https://cloud.githubusercontent.com/assets/178418/3284293/ca04778e-f528-11e3-8461-a196158b1a7d.png)

> @all ちょっち、私用でばたばたしてるけど、メール出して無事に予約できました！

との事だったのでクローズします

**Comment by asonas** [comment]
:ant: \* 10
