### ISSUE TITLE
#2 メンバー確定

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#19]
### 40m
- 部長 aka RooandQoo (TRANCE)
- 副部長 aka jigsaw (IDOLCORE #2)
- 便座チープネス (HIPHOP)
### 30m
- 顧問 aka asonas (NERD)
- mactkg (INTERNET)
- XEN
- toihrk
- sora_h (2.5D)
- furaji
- Maenox
- dachiba

**Comment by asonas** [comment]
前回のイベントで感化されてやりたそうにしてた人は
sora_h
furaji
Maenox
の3人かな。
あと6周年記念パーティで興味を持ってくれた人がいたぽいけどID聞くの忘れてた...

**Comment by e-jigsaw** [comment]
Maenoxさん皿回しマシン購入して毎日回しているとのことです

**Comment by toihrk** [comment]
栃木組、y.taqはまだ日程的に怪しいからわからないとのこと。
XENは明日聞いてみます。
ボクは出してもらえるならめちゃくちゃ練習して臨むつもりです！

**Comment by RooandQoo** [comment]
といくんは不動の1番手っぽい

**Comment by toihrk** [comment]
マジですか〜

**Comment by toihrk** [comment]
さっき電話してXENに確認したら「出たい〜！」とのことです〜

**Comment by e-jigsaw** [comment]
XEN最高

**Comment by RooandQoo** [comment]
## 出そうな人

部長 aka RooandQoo
副部長 aka jigsaw
顧問 aka asonas
mactkg
XEN
toihrk
便座チープネス

## 出たがってる人

sora_h
furaji
Maenox
dachiba

## 要確認

## 不参加

八嶋
maccha
y.taq

**Comment by RooandQoo** [comment]
便座チープネス「出る」

**Comment by asonas** [comment]
八嶋くん、予定が合わずとのことー

**Comment by RooandQoo** [comment]
おｋ

**Comment by asonas** [comment]
今週中にメンバー決めて、来週には機材の手配をしましょう。

**Comment by asonas** [comment]
toiくんにy_taqくんの予定を聞いてるなう

**Comment by RooandQoo** [comment]
y_taqくんが出る→1人30分
出ない→40分枠*3ができる

**Comment by asonas** [comment]
y_taqくん、インターンと被って難しいとのこと..!!

**Comment by RooandQoo** [comment]
## member

### 40m
- 部長 aka RooandQoo (TRANCE)
- 副部長 aka jigsaw (人生 #2)
- 便座チープネス (HIPHOP)

### 30m
- 顧問 aka asonas (NERD)
- mactkg (INTERNET)
- XEN
- toihrk
- sora_h
- furaji
- Maenox
- dachiba

**Comment by asonas** [comment]
あ、僕30分でいいですよー

**Comment by mactkg** [comment]
よく考えたら8/31はてなインターン時期と被ってた気がする…

**Comment by asonas** [comment]
まじで....

**Comment by RooandQoo** [comment]
まじで…

**Comment by june29** [comment]
まじで…

**Comment by asonas** [comment]
http://developer.hatenastaff.com/entry/2014/06/17/111849

> 2014年8月11日（月）〜9月5日（金）平日のみ20日間

hyo-

**Comment by mactkg** [comment]
2014年8月11日（月）〜9月5日（金）平日のみ20日間

**Comment by RooandQoo** [comment]
＿人人人人人人人人＿
＞　突然のjune29　＜
￣Y^Y^Y^Y^Y^Y^Y￣

**Comment by RooandQoo** [comment]
やめちまえ

**Comment by mactkg** [comment]
部長勢いがある

**Comment by asonas** [comment]
平日のみなので休日は参加可能なのでは????

**Comment by mactkg** [comment]
いけそう

**Comment by asonas** [comment]
まじでか（無理ぽかったら普通にはてなインターン優先してもらっていいですよー）

**Comment by RooandQoo** [comment]
顧問に同意

**Comment by e-jigsaw** [comment]
いつの間にかジャンル名が「人生#2」になっていた

**Comment by asonas** [comment]
「人生。それは、」

**Comment by e-jigsaw** [comment]
アイドル

**Comment by RooandQoo** [comment]
まっくんが来れなくなったら俺が50分もらう

**Comment by mactkg** [comment]
@RooandQoo おっそういう感じにしてもらえると助かります

**Comment by asonas** [comment]
@mactkg TJはやりたいなーと思うのでなんかよしなにやりとりしましょう。

**Comment by mactkg** [comment]
@asonas 使ってる機材とか送ったりすることは全然可能なのでそこに関してはやりましょう！

**Comment by sorah** [comment]
- 40m くれ

**Comment by RooandQoo** [comment]
@sorah まっくんが来れなくなったら で

**Comment by sorah** [comment]
ok

あ、カテゴリ2.5Dで

**Comment by asonas** [comment]
確定したのでclose~
