### ISSUE TITLE
TTきめる

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#20]

**Comment by asonas** [comment]
| time | time |
| --- | --- |
| 30m | toihrk |
| 30m | XEN |
| 30m | Maenox |
| 30m | dachiba |
| 30m | furaji |
| 30m | furaji's friend |
| 40m | frkout |
| 30m | sora_h |
| 30m | asonas |
| 40m | jigsaw |
| 40m | RooandQoo |

順番こんな感じでどうすかね

**Comment by e-jigsaw** [comment]
:muscle:

**Comment by RooandQoo** [comment]
:ok_woman:

**Comment by asonas** [comment]
| time | time |
| --- | --- |
| 13:00 | toihrk |
| 13:30 | XEN |
| 14:00 | Maenox |
| 14:30 | dachiba |
| 15:00 | furaji |
| 15:30 | furaji's friend |
| 16:00 | frkout |
| 16:40 | sora_h |
| 17:10 | asonas |
| 17:40 | jigsaw |
| 18:20 | RooandQoo |

**Comment by e-jigsaw** [comment]
:100:

**Comment by asonas** [comment]
アップロードした
http://kosendj-bu.in
