### ISSUE TITLE
フライヤー作る

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#21]
今度は印刷しようぜ〜〜

**Comment by e-jigsaw** [comment]
死体

**Comment by RooandQoo** [comment]
とはいえどこで撒くのか

**Comment by asonas** [comment]
フライヤーの制作はどなたにお願いしますかねー？
npyamaくん？namamanaさん？それかまた別の人かなー？

**Comment by RooandQoo** [comment]
npyamaくん行ってみましょ

**Comment by RooandQoo** [comment]
これ全然動けんかった（申し訳ないです
クリティカルなものでもないので今回はナシで…
