### ISSUE TITLE
TJの用意をする

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#23]
主に機材の受け渡しなど

**Comment by mactkg** [comment]
Updateもしなきゃ！（ソースも~~後悔~~公開しないと）

**Comment by e-jigsaw** [comment]
わたくしもそろそろ考えネバダ州

**Comment by e-jigsaw** [comment]
まっくんこれない対策どうしよう...

**Comment by asonas** [comment]
機材とアプリケーションは僕が受け取るので当日はみんなで持ち回しでフェーダいじる感じかねぇ

**Comment by e-jigsaw** [comment]
なるほむー

**Comment by mactkg** [comment]
ソースコード公開についてなんですがrepoどうしましょう。。。
https://github.com/kosendj/tumblr-jocky にeffectorってディレクトリを作って、その中に僕のアプリケーション入れるのでも良いですが、

よくよく考えると僕のシステムはGifのVJシステムとして切り出すことが出来て、@e-jigsaw のシステムを使うことでTumblrと融合出来るとも考えられるかな〜と思ったりしております。

つまるところ迷ってるので、みなさんの意見が聞きたいところです cc/ @asonas

**Comment by e-jigsaw** [comment]
わたくしもシステム構成迷ってるんですが、ちょろっと話が出ていた ws つかってみんなで VJ みたいな機構つくれるとよいのかなー、とおもいつつ...
