### ISSUE TITLE
機材リスト

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#24]
| name | 機材の持ち込みか常設機材 | 機材の名前 |
| --- | --- | --- |
| asonas | 持ち込み | iPad + Z1 + KaossPad |
| RooandQoo | 持ち込み | PCDJ + DDJ-WeGo |
| jigsaw | 持ち込み | PCDJ + S2 |
| mactkg | 持ち込み | PCDJ + Z1 + X1 |
| toihrk | 持ち込み | PCDJ + DDJ-SB |
| xen | 常設機材 | CDJ Pioneer CDJ-1000mk3 x2 DJ Mixer Pioneer DJM-800 |
| frkout | 常設機材 | CDJ Pioneer CDJ-1000mk3 x2 DJ Mixer Pioneer DJM-800 |
| sora_h | 持ち込み |  |
| dachiba | DDJ-SB | GAME MUSIC |
| Maenox | 持ち込み | DDJ-SB |
| furaji | 持ち込み | iPad |

**Comment by asonas** [comment]
助かる...!!

**Comment by RooandQoo** [comment]
でしょ〜

**Comment by mactkg** [comment]
切り替えたりするの面倒なのでもし可能なら @e-jigsaw の機材にUSBメモリーで曲持って行くとかのほうが良いかなーと思ったのでタイムテーブルによってはそれで行こうかなと思います

**Comment by asonas** [comment]
機材fixしたので僕の方からsabacoさんにメール送ります

**Comment by asonas** [comment]
http://sabaco.jp/e/3347/
機材変わったので
CDJ-2000Nexus
DJM-900Nexus
以上のふたつをレンタルする

**Comment by mactkg** [comment]
便利。。。。。。。。。。。。。。。。。。。。。。:tada:
