### ISSUE TITLE
DJメンバー

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#27]
- rooandqoo
- jigsaw
- asonas
- dachiba + maccha
- Fake Chord Union (maru + furaji + 八嶋)
- mactkg
- Maenox
- toihrk
- sorah
- y_taq
- XEN
- minami106

**Comment by mactkg** [comment]
多い！

**Comment by asonas** [comment]
https://twitter.com/furaji/status/519453154048364544
とのこと

**Comment by mactkg** [comment]
かっこいい

**Comment by mactkg** [comment]
3人でプレイするのか〜楽しそう

**Comment by furaji** [comment]
人口密度高まる

**Comment by asonas** [comment]
草案

![2014-10-07 20 55 19](https://cloud.githubusercontent.com/assets/630181/4541755/db0a1838-4e18-11e4-802a-540d6d6f86c4.png)

**Comment by RooandQoo** [comment]
asonas VS macktg 見たい

**Comment by mactkg** [comment]
![hi](http://mrwgifs.com/wp-content/uploads/2013/07/Morpheus-Come-At-Me-Bro-Reaction-Gif-In-The-Matrix.gif)
