### ISSUE TITLE
TT

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#28]
| time | name | genre |
| --- | --- | --- |
| 14:00 | toihrk | 遅刻 |
| 14:30 | y_raq | UK HARDCORE |
| 15:00 | Maenox | アニソン |
| 15:30 | XEN | EDM |
| 16:00 | dachiba & maccha | GAME MUSIC |
| 16:30 | minami106 | POPS |
| 16:50 | RooandQoo | Progressive House |
| 17:25 | Fake Chord Union(maru + furaji + 八嶋) | B2B2B |
| 18:10 | sora_h | 原曲 |
| 18:40 | asonas vs mactkg | INTERNET |
| 19:25 | jigsaw | IDOLCORE FINALE |

**Comment by e-jigsaw** [comment]
:dancer:
