### ISSUE TITLE
AWSアカウント作ろうと思う

### ISSUE THREAD

**Issue by sorah** [kosendj/bu#29]
kosendj-bu オペレーション担当の sorah だよ

GJ とかでもろもろ次回頑張ろうと思うのでわたし支払いの AWS アカウントを作ろうと思ってるんだけどいいかね (s3 とか cloudfront とか ec2 (開催当日のみ) とか使うよ)

それに伴って DNS だけそのアカウントの R53 でホストできると良いかなーとも思ってるよ

必要っぽい人には権限も配るよ

というわけでコメントをください

**Comment by asonas** [comment]
どうもどうも
kosendj-bu.inのドメインをR53で管理してるのは僕でする。
GJで何か必要なものがあればご用命くださいませ。

ちなみに ec2 にした理由とかあります？herokuだとレイテンシとかいざってときに自由にsshできる方が便利とかって感じですかね？

**Comment by sorah** [comment]
まあそんなかんじ。GJ app 以外でもちょこちょこ使う予感。開催時以外は heroku へ戻そ〜かな〜みたいな。

あとでアカウントつくるんで hosted zone 移動させよう

**Comment by sorah** [comment]
アカウントは作っていろいろやり始めた kosendj/ops
