### ISSUE TITLE
タイムテーブルを決める

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#3]

**Comment by asonas** [comment]
メモから書き出しです

| 名前 | 時間 |
| --- | --- |
| rooandqoo | 50分 |
| asonas | 40分 |
| toihrk | 30分 |
| maccha | 30分 |
| mactkg | 30分 |
| neo6120 | 30分 |
| 小山高専生A | ? |
| 小山高専生B | ? |
| frkout | 無限 |

@maccha さんと @toihrk くんの時間は仮なので、自分がDJしたい時間を教えてください
また小山高専の方が参加されるとのことなので、 @toihrk 君経由でいいので名前とDJしたい時間を教えて下さい。

**Comment by maccha** [comment]
DJは初ですし、30分でお願いします！

**Comment by asonas** [comment]
:+1:

**Comment by asonas** [comment]
| time | DJ |
| --- | --- |
| 15:00 | toihrk (HAEDCORE TECHNO) |
| 15:40 | y_taq (HARDCORE) |
| 16:10 | XEN (HARDSTYLE) |
| 16:40 | 八嶋 (DRUM'N'BASS) |
| 17:10 | maccha (game music) |
| 17:40 | DJ 顧問 a.k.a. asonas (NERD) |
| 18:10 | mactkg (INTERNET) |
| 18:40 | frkout (TBD) |
| 19:30 | DJ 副部長 a.k.a. jigsaw (IDOLCORE) |
| 20:10 | DJ 部長 a.k.a. RooandQoo (trance) |

お待たせしました。
こんな感じでどうでしょうかー？

**Comment by asonas** [comment]
部長で締めてもよい気がしてきた

**Comment by e-jigsaw** [comment]
夕方が怖い

**Comment by e-jigsaw** [comment]
:sunrise:

**Comment by asonas** [comment]
ああ 夜が来て 街に闇が降るよ

**Comment by toihrk** [comment]
アッアッ！１番最初！キンチョ〜

**Comment by asonas** [comment]
わいわい

**Comment by asonas** [comment]
部長で締めよう

**Comment by RooandQoo** [comment]
:sweat:

**Comment by RooandQoo** [comment]
がんばるぞ

**Comment by asonas** [comment]
よっしゃよっしゃ〜

**Comment by e-jigsaw** [comment]
あ、あれ！？

**Comment by e-jigsaw** [comment]
ラス前に変わってるやんキー

**Comment by RooandQoo** [comment]
パワーある人はピークタイムに置きたい

**Comment by RooandQoo** [comment]
| time | DJ |
| --- | --- |
| 15:00 | toihrk (HAEDCORE TECHNO) |
| 15:40 | y_taq (HARDCORE) |
| 16:10 | XEN (HARDSTYLE) |
| 16:40 | 八嶋 (DRUM'N'BASS) |
| 17:10 | maccha (game music) |
| 17:40 | DJ 副部長 a.k.a. jigsaw (IDOLCORE) |
| 18:20 | mactkg (INTERNET) |
| 18:50 | DJ 顧問 a.k.a. asonas (NERD) |
| 19:20 | frkout (HIPHOP) |
| 20:10 | DJ 部長 a.k.a. RooandQoo (TRANCE) |

でどうですか

**Comment by asonas** [comment]
mactkg -> asonas -> frkout -> rooandqoo でどうでしょう。

**Comment by RooandQoo** [comment]
いいっすよ〜

**Comment by asonas** [comment]
上更新した

**Comment by e-jigsaw** [comment]
おっ

**Comment by asonas** [comment]
https://github.com/RooandQoo/kosendj-bu/issues/3#issuecomment-42790073

るくちゃんのコメントにあるTTでどうかしらね〜。

**Comment by e-jigsaw** [comment]
特に僕は異存ないです

**Comment by mactkg** [comment]
[![LGTM](http://www.lgtm.in/p/E2rTX3L5q)](http://www.lgtm.in/i/E2rTX3L5q)

**Comment by asonas** [comment]
TJで流したいgifだ！！！！！！！！！！！！！！！！！！！！！！

**Comment by maccha** [comment]
TT、おけで〜す！

**Comment by asonas** [comment]
出揃ったのでCloseします！！！！！！！
