### ISSUE TITLE
フライヤーをつくる

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#4]

**Comment by e-jigsaw** [comment]
@npyama を召喚しましょ☆☆☆☆☆

**Comment by npyama** [comment]
召喚された

**Comment by e-jigsaw** [comment]
イェーイ

**Comment by e-jigsaw** [comment]
ロゴ(仮)が https://suzuri.jp/namamana/5060/t-shirt/s/white なのでこれに寄せていく感じかなあ

**Comment by npyama** [comment]
ロゴのデータ欲しさあります

**Comment by e-jigsaw** [comment]
@asonas ping

**Comment by asonas** [comment]
了解ですー

**Comment by asonas** [comment]
![kosendj-bu](https://cloud.githubusercontent.com/assets/630181/2722644/9ba237f0-c58a-11e3-8ba6-9a4f72d6be44.png)

とりあえず、印刷できるぐらいのpngで用意しました。
必要とあれば色々な形式で用意します。

**Comment by npyama** [comment]
ｱｻﾞｰｯｯｽ！！！！！

**Comment by mactkg** [comment]
デカっ

**Comment by e-jigsaw** [comment]
でかっ

**Comment by mactkg** [comment]
DJ部のロゴ何回も見るたびに良さが出てきてスルメっぽい

**Comment by npyama** [comment]
ようやく取り掛かれそうであわわわわな感じで申し訳ないです。
フライヤーに書かなきゃいけない情報欲しいんですけど、
どなたか纏めて投げてもらってもいいですかー！

**Comment by e-jigsaw** [comment]
おおむね https://github.com/RooandQoo/kosendj-bu/blob/master/README.md の通りで場所が http://sabaco.jp/access/ ぐらいかなあ

**Comment by npyama** [comment]
TJのあたりどうしたらいいか頼む〜

**Comment by asonas** [comment]
@npyama 
https://github.com/RooandQoo/kosendj-bu/blob/master/README.md
少し追記などしましたー。
TJについても一言だけですが書きました。
画面とかあればいいのですが、まだ開発途中なので用意できるものもあまりないです(ごめんなさい...)
機能としては、Tumblrから画像や動画などをリブログして、そのコンテンツにエフェクトをかけてスクリーンに映写してVJぽく演出できるものです。

現状の情報量が少ないので、コピーライト的に文章をワンラインで入れるだけでもいいと思うのですがいかがでしょうか。

**Comment by asonas** [comment]
@npyama 
こちらいかがでしょうかー？
何かブロッキングされていることがあれば相談にのりますー。

**Comment by npyama** [comment]
GWにひと通り作ったけどめちゃださ案件でげんなりしたのでもう少し待って頂けると幸いです！申し訳ないです！！

**Comment by asonas** [comment]
@npyama はーい、了解ですー。出来上がったらWebに掲載しようと思うのでよろしくお願いします〜

**Comment by npyama** [comment]
今週末にはあげます！！申し訳ないです！！！

**Comment by asonas** [comment]
わーい。まってまーす

**Comment by npyama** [comment]
![kosendj-bu](https://cloud.githubusercontent.com/assets/1782255/3016017/19fab6d4-df69-11e3-93f3-9ffe678c7715.png)

大変遅れて申し訳ない気持ちでいっぱいですがよければ使ってくださいくらいの気持ち

**Comment by mactkg** [comment]
@npyama わはー！！！ありがとうございます！

DATEの時間が違うような気がするのでアップデート可能でしょうか…？
5/30(Sat) 15:00〜21:00 です。

**Comment by asonas** [comment]
あ、そして30日ではな31日ですね・・・

**Comment by asonas** [comment]
@npyama 
ありがとうございます！
とりあえず日にちが治ったらWebにも掲載していこうと思います！

**Comment by npyama** [comment]
![kosendj-bu](https://cloud.githubusercontent.com/assets/1782255/3021005/d17b615c-dfa8-11e3-97dd-78c3b4339954.png)
ありがとうございます！！！！修正しました！！！！！！！

**Comment by e-jigsaw** [comment]
DJのところ、最新版にした方がよいかも？

```
15:00   toihrk (HARDCORE TECHNO)
15:40   y_taq (HARDCORE TECHNO)
16:10   XEN (HARDSTYLE)
16:40   八嶋 (DRUM'N'BASS)
17:10   maccha (GAME MUSIC)
17:40   DJ 副部長 a.k.a. jigsaw (IDOLCORE)
18:20   mactkg (INTERNET)
18:50   DJ 顧問 a.k.a. asonas (NERD)
19:20   便座チープネス (HIPHOP)
20:10   DJ 部長 a.k.a. RooandQoo (TRANCE)
```

**Comment by RooandQoo** [comment]
↑微妙に直した

**Comment by RooandQoo** [comment]
一人何分かって情報は載せなくてもいい気がするな〜

**Comment by e-jigsaw** [comment]
たし蟹そう鴨

**Comment by mactkg** [comment]
その鳥ですね（無理がある）

**Comment by npyama** [comment]
![kosendj-bu](https://cloud.githubusercontent.com/assets/1782255/3027907/49256c10-e027-11e3-9ec6-7cab8216ff89.png)

烏賊がなもんでしょうか？！？

**Comment by RooandQoo** [comment]
最高・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・

**Comment by e-jigsaw** [comment]
:+1:

**Comment by asonas** [comment]
最高！！！！！！！！！！！！！！！！！！！！！！！

**Comment by asonas** [comment]
http://instagram.com/p/oP6FvctBUB/
テンション上がって印刷してみた。

CMYK, 横3000pxぐらいのデータがあるとももう少し色味とかはっきりしそう

**Comment by npyama** [comment]
ｳｯ色怖い
aiファイル投げたいんだけどどうしたらいいかな(おろおろ
取り敢えずDropboxで共有するんだな(おろおろ

http://goo.gl/zYMRtS

**Comment by asonas** [comment]
がんばって印刷用データつくろうとしたけど、時間的にむりでした。。。
フライヤー制作ありがとうございました！！！！！！！！！！！！！
