### ISSUE TITLE
イベントタイトルを決める

### ISSUE THREAD

**Issue by RooandQoo** [kosendj/bu#5]

**Comment by RooandQoo** [comment]
@asonas 氏！カッケーのオナシャス！

**Comment by asonas** [comment]
うぇいうぇい

**Comment by RooandQoo** [comment]
高専らしくCとTから始まる2単語の名前にできるといいような気がする

**Comment by e-jigsaw** [comment]
なんとかNCTみたいな N(erd) C(...) T(rance)

**Comment by asonas** [comment]
Nerd Core Trance（曲のジャンルだ。。。）

**Comment by asonas** [comment]
Nanka Chou Tanoshii

**Comment by mactkg** [comment]
> Nanka Chou Tanoshii

:laughing: :laughing: :laughing:

**Comment by e-jigsaw** [comment]
> Nanka Chou Tanoshii

ii

**Comment by asonas** [comment]
**Namby-Camby-Techy**

Namby ... おちゃらけた
Campy(camp) ... 奇抜でこっけいな
Techy ... てくのろじ〜

campyが結構やっつけかん

**Comment by asonas** [comment]
Chummy ... 打ち解けた・親しい

**Comment by asonas** [comment]
Nanka Chou Tanoshii いい気がしてきた。

**Comment by e-jigsaw** [comment]
Nanka Chou Tanoshii

**Comment by asonas** [comment]
Nanka Chou Tanoshii気がしてきた

**Comment by e-jigsaw** [comment]
kosendj-bu でいいのかな

**Comment by asonas** [comment]
よいとおもいます！！！！！！！！！！！！！！

**Comment by RooandQoo** [comment]
おもいます！！！！！！！！！！
