### ISSUE TITLE
TJ部(Tumblr Jockey)

### ISSUE THREAD

**Issue by e-jigsaw** [kosendj/bu#6]
# 目標
- 会場のひとたちがリブログしたphotoがスクリーンに出せる
- 会場のひとたちがリブログしたphotoをすぐリブログできる
- 枯渇に備えてタグでphotoを出せるようにする
- スクリーンのphotoにエフェクトがかけられる
## なんとなくの分担

@e-jigsaw: tumblr
@mactkg: エフェクタ
### Ultra Fast Tagging Tool
- ヘビータンブリスタ向け
- 楽しくタグ付けやってるうちにどんどんオレのtumblrがタグ付けされてイクゥゥゥ！っていうやつ
- 事前準備用につくる
### tumblr-bu
- 会場のひとにOAuth認証してもらう
- モバイルデバイスに最適化する
- tumblr-buを通じてリブログすると、自分のtumblogとtumblr-buのtumblogにクロスリブログされる
### tumblub-kai
- http://tumblub.jgs.me 改
- tag出しができる
- tumblr-buのtumblogを出せる
- @mactkg の扱えるような状態に出力できるようにする
## エフェクタまわり

主に @mactkg 任せ(Quartzとか使うのがよいかしら？)

**Comment by e-jigsaw** [comment]
細かいところを別issueに分けるか、リポジトリを分けてそこでやるか悩み〜〜

**Comment by mactkg** [comment]
## エフェクタ

openFrameworksのアドオンで色々エフェクタをかけられるのがあるので、それを使おうかなーと考え中です。GLSLとかでシェーダーを書いても良いかも（書けんのかな…）。

色々ツールはあるんですが、いじり慣れてるのはこれなので。

## リソースのやり取り

> @mactkg の扱えるような状態に出力できるようにする

rblgされると
- サーバが検出する
- データを取ってきて一旦ローカルに保存
- ローカルの画像へのURLをSocket/WebSocketでoFへ
- oFが画像を読んでかっこ良くする

が出来ると良いかなと思います。色々メッセージのやり取りも出来たほうが良いと思うので、jsonで送ってくれた方が良いかもしれません。jpg/png/tiff/gifなど画像ならなんでもいけるはずです。

> - ローカルの画像へのURLをSocket/WebSocketでoFへ

ローカルに一旦置いておきたいのは、万が一の時にすぐ画像を引き出せるかなーと思ったからですが、もしかしたら必要ないかもしれません。ここは要検討かと。

あと

> 枯渇に備えてタグでphotoを出せるようにする

ってのむっちゃいいですね。僕は僕でサーバが死んだ時のために、過去の画像から適当に回してこれる仕組みも用意しておきたい。

## issuesの運用

> 細かいところを別issueに分けるか、リポジトリを分けてそこでやるか悩み〜〜

リポジトリを分けてしまったほうが良いのかなーと思ったりしますけどどうでしょう。色々ごちゃつきそうで。

**Comment by e-jigsaw** [comment]
> jsonで送ってくれた方が良いかもしれません。

同意〜〜

**Comment by e-jigsaw** [comment]
> データを取ってきて一旦ローカルに保存

そこそこの画像のサイズのをDLしようとするとどうしても遅延するのでローカルで持っておいた方がいいとおもうー。tumblubも最初遅かったので常に100枚ぐらいストックしておく仕組みにしてる。

**Comment by e-jigsaw** [comment]
TJ部(仮)でリポジトリにするか、そもそもサバクラで同一リポジトリにする意味があまりないような気もするのでそこもわけちゃって、ドキュメントをここのwiki使うのもアリな気がする

**Comment by mactkg** [comment]
> tumblubも最初遅かったので常に100枚ぐらいストックしておく仕組みにしてる。

なるほどー。ReblogMachineとかなんかはまさにこんな感じですよね

**Comment by mactkg** [comment]
> TJ部(仮)でリポジトリにするか、そもそもサバクラで同一リポジトリにする意味があまりないような気もするのでそこもわけちゃって、ドキュメントをここのwiki使うのもアリな気がする

いいですねー。GithubはrepoまたいでIssue参照とかできるしなんとかなりそう :tada:

**Comment by e-jigsaw** [comment]
:ok_woman:

**Comment by mactkg** [comment]
BPMに合わせてGIFを再生してみた。
https://www.youtube.com/watch?v=NoXwIacOudc&feature=youtu.be

進捗とか色々どうやって管理しよう〜。kosendj/tjとか作る感じですかね。

**Comment by e-jigsaw** [comment]
- tj
- tj-server
- tj-client
- tj-effector

みたいな構成になるかなあ、名前はもっと考えるとして。

**Comment by e-jigsaw** [comment]
そういえば、joc.kyドメインが空いてるらしい

**Comment by e-jigsaw** [comment]
gif が bpm に合わせて動くの面白い(yes yes がじわじわくる)

**Comment by e-jigsaw** [comment]
続きは https://github.com/kosendj/tumblr-jocky/issues で
