### ISSUE TITLE
@toihrk がDJコンを買う

### ISSUE THREAD

**Issue by e-jigsaw** [kosendj/bu#7]
おすすめ情報がここに集まってくる

**Comment by asonas** [comment]
ピクシブ社にも置いてあるDJコントローラでめっちゃいいです
PCDJもCDJもUSBに音楽突っ込んでDJもできる最高なやつです。お値段も最高です。

http://pioneerdj.com/japanese/products/djsystem/xdj-r1.html

**Comment by mactkg** [comment]
XDJ-R1、100kもするのか〜〜〜〜。

僕はそこそこサクッと買えそうなTRAKTOR Z1を買おうかな〜と思ってますけど、これだとミキシングくらいしか出来ないのよね
http://www.native-instruments.com/jp/products/traktor/traktor-for-ios/traktor-kontrol-z1/

**Comment by asonas** [comment]
Z1カジュアルに部屋DJできるのでいいですよ。

**Comment by mactkg** [comment]
:dancer:  :cd: :dancer:

**Comment by toihrk** [comment]
XDJ-R1かっこよさ〜
予算的にはZ1はガツンな感じある

**Comment by RooandQoo** [comment]
Wego安くていいですよ
http://www.amazon.co.jp/Pioneer-DJ-CONTROLLER-%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF-DDJ-WeGO2-K/dp/B00EZGX066

**Comment by toihrk** [comment]
Pioneer！！！
WegoとDDJ-SBっていうので迷ってます:weary:
http://www.soundhouse.co.jp/sp/shop/productdetail.asp?item=583%5eddjsb%5e%5e

**Comment by mactkg** [comment]
うおーZ1買おうと思ってたけどDDJ-SBとかお手頃でいいな。。。。

**Comment by asonas** [comment]
増税前がチャンスなのでは？？？？？？？？？

**Comment by toihrk** [comment]
$BCMCJ8+$F(BDDJ-SB$B%]%A$j$^$7$?!<!*(B
$B%o%$%o%$!A(B

**Comment by asonas** [comment]
メールってまだ文字化けするんだなぁ

**Comment by e-jigsaw** [comment]
メールで投稿できるんだ

**Comment by toihrk** [comment]
https://github.com/RooandQoo/kosendj-bu/issues/7#issuecomment-38790385
文字化け恥ずかしい... 

値段で決めてしまってDDJ-SBポチりました。
支払いも昨日のうちに済ませたので、そのうち届くと思います～！！！
楽しみ:bowtie:

**Comment by mactkg** [comment]
:tada:

**Comment by asonas** [comment]
:sparkles:

**Comment by e-jigsaw** [comment]
:dancer:

**Comment by asonas** [comment]
各位 といくんの元にコントローラが届いたらこのIssue閉じましょう

**Comment by toihrk** [comment]
届いて、今さっき開封して、少し遊びました！！！
ヤバイ！！！
楽しい〜！！！
眠い！！！
ご協力ありがとうございました〜！！！

**Comment by e-jigsaw** [comment]
:confetti_ball:

**Comment by asonas** [comment]
:clap:
