### ISSUE TITLE
キックオフ飲み会しませんか

### ISSUE THREAD

**Issue by asonas** [kosendj/bu#8]
どういうパーティにしたいかとかどういう人を呼びたいかとかその辺のブレストとかみんながどんなことを思っているかを知りたいので、かる～い飲み会をやりませんか？

日時は未定だけど4月の頭とかに予定できるとよさそう。
@HirokiTOI くんが一番遠いのでトイ君が空いている時間に合わせようと思います。

**Comment by RooandQoo** [comment]
:+1:

**Comment by e-jigsaw** [comment]
:+1:

**Comment by mactkg** [comment]
:+1: :bear:

**Comment by mactkg** [comment]
s/:bear:/:beer:/

**Comment by asonas** [comment]
ｸﾏｰ

**Comment by toihrk** [comment]
バイト先の4月前半のシフトと学校の兼ね合いからだと3,4,11,13が空いてます、ご都合いかがでしょうか〜？

**Comment by e-jigsaw** [comment]
新卒マンなので予定が全く読めないのですが、11,13は宿泊研修なので少なくとも無理そうであります

**Comment by asonas** [comment]
3,4の夜あたりで予定決めますかー。
僕は両日大丈夫ですー。
@RooandQoo @mactkg はいかがですか？

**Comment by mactkg** [comment]
4は20:30までバイトあるので3の方が都合良いです！

**Comment by RooandQoo** [comment]
3日に研修から帰ってきて、4日にその打ち上げがあるっぽいので、やるなら3日が良いです。

**Comment by asonas** [comment]
3日にしましょう！！！！！！！！！！！！！！！！！！！！！！！！！！
@RooandQoo @e-jigsaw @mactkg @HirokiTOI

**Comment by RooandQoo** [comment]
:ok_hand:

**Comment by asonas** [comment]
19:30ごろから代々木か渋谷あたりを考えてますが、いかがでしょうか。

**Comment by mactkg** [comment]
:ok_woman:

**Comment by toihrk** [comment]
上京ダァー上京ダァー！！！

**Comment by RooandQoo** [comment]
研修、3-4でした˚‧º·(˚ ˃̣̣̥᷄⌓˂̣̣̥᷅ )‧º·˚

**Comment by asonas** [comment]
oh

**Comment by asonas** [comment]
@RooandQoo 4日はそのまま打ち上げって感じかな？

**Comment by e-jigsaw** [comment]
どうなったんだどうなったんだ！？！？

**Comment by asonas** [comment]
とりあえず3日にやって、僕とるーくちゃんは12日に会う感じなので、その日に来れる人たちでもう一回やってもいい気がしてきた。

**Comment by e-jigsaw** [comment]
とりあえず3日かな〜〜〜

僕もまだ確定難しいです

**Comment by RooandQoo** [comment]
4日は打ち上げですね。。すみません！

**Comment by asonas** [comment]
みんなが揃えないのは残念だけど、4月3日と4月12日の2回にわけて開催しましょー。
4月3日は19時半ぐらいに代々木駅のTAKOYOYOGIでやろうと思います。あとで予約しますね。
4月12日はもうちょっと先にきめます。

**Comment by e-jigsaw** [comment]
きっと、いける、予定では、いける、はず

**Comment by toihrk** [comment]
12日、18時までバイトで次の日は休みなので、ちょっと遅い時間だったらトーキョー行けます！たぶん！

**Comment by e-jigsaw** [comment]
めっちゃ申し訳ないんすけど、3日微妙でむしろ12日のほうがいけるような気がしてまいりました(合宿が今週末なの勘違いしてた)

**Comment by mactkg** [comment]
12いけます

**Comment by asonas** [comment]
とりあえず、明日予約したので明日来れる人でやりましょ〜
19時25分ぐらいに代々木駅に集合してくださいませ〜

12日も有力なの把握です〜

**Comment by asonas** [comment]
@RooandQoo @e-jigsaw @mactkg @toihrk 各位12日はいかがでしょうか？（リマインドでした）

**Comment by mactkg** [comment]
18:00くらいまで秋葉原でバイトで、その後あいてます。

**Comment by RooandQoo** [comment]
日中〜夜は空いておりますが、20時から会社の用事で渋谷に行かないといけなくなっちゃったので、まっくんやといくんとは一瞬しか会えないかも…！

**Comment by e-jigsaw** [comment]
たぶん空いてます〜

**Comment by toihrk** [comment]
ごめんなさい。明日たぶん行けないです〜:astonished:

**Comment by asonas** [comment]
残念〜

**Comment by mactkg** [comment]
バイトが17:00で上がれるようになったっぽいです

**Comment by asonas** [comment]
本日18時に渋谷の 北海道でやろうと思います。
18時に北海道のあるビルの下あたりに集合しましょう

http://r.gnavi.co.jp/g086283/

**Comment by e-jigsaw** [comment]
渋谷の北海道という字面が意味不明すぎて笑った

**Comment by asonas** [comment]
ビルわかんなかったらタイステのあたりにくるとよさそう

**Comment by e-jigsaw** [comment]
いろいろ決まった

**Comment by asonas** [comment]
:v:
