### ISSUE TITLE
リポジトリの移行

### ISSUE THREAD

**Issue by e-jigsaw** [kosendj/bu#9]
https://github.com/kosendj/bu ここへこのリポジトリを移行しよう〜〜〜

**Comment by RooandQoo** [comment]
移行 やり方

**Comment by asonas** [comment]
あっ、オーガナイゼーションのオーナーです（こんばんは）
特にTumblrJockeyをOSSで公開したいという名の下にオーガナイゼーションとリポジトリをつくりました。
イベント開催系のリポジトリをprivateリポジトリのまま移すとなるとオーガナイゼーションのアカウントのほうで課金をしなくてはならなるのでご注意ください。

例えば、高専カンファで言えば、080tokyoや083camphor-のようにオープンなイベント開催準備のリポジトリとしてpublicなリポジトリにするか、それともprivateなリポジトリにするかの判断はこのリポジトリのオーナーの @RooandQoo くんに任せたいと思います。

参考リンクです。
https://github.com/kosenconf/080tokyo
https://github.com/kosenconf/kosenconf-kyoto-02

**Comment by asonas** [comment]
このリポジトリの行方など開催準備にかんすることも含めて #8 の飲み会で決められたらなぁと思いましたー

**Comment by RooandQoo** [comment]
開催後にpublicにするつもりではいたので、開催後にそちらに移行する形だとまずいですかね！

**Comment by asonas** [comment]
よいですー！！
TumblrJockeyは向こうのリポジトリでつくりますかー。

**Comment by RooandQoo** [comment]
:ok:

**Comment by RooandQoo** [comment]
終わったのでpublicにしちゃいます？？よ？？

**Comment by asonas** [comment]
:ok_woman:

**Comment by asonas** [comment]
kosendjにTransferしてもらえればよさそう

**Comment by asonas** [comment]
https://github.com/kosendj/bu
